Implment routing
JokeCam/frontend-dynamic-content pull request #5
Opened 2022-02-02 08:02 UTC by JokeCam

2022-02-02 08:39 UTC, FoZzTH requested changes

2022-02-02 08:39 UTC, FoZzTH commented on src/components/Header/Header.js
> +        if (!isProfileButtonActive) {
функция поменяла своё поведение. ты заменил не на эквивалентную. так и планировалось?

2022-02-02 08:39 UTC, FoZzTH commented on src/components/Header/Header.js
> +        if (!isHomeButtonActive) {
тут так же как и в коменте с такой же функцией

2022-02-02 08:40 UTC, JokeCam commented on src/components/Header/Header.js
> +        if (!isProfileButtonActive) {
Так и планировалось!

2022-02-08 22:19 UTC, FoZzTH approved these changes

2022-02-09 07:44 UTC, merged